import Head from 'next/head'
import NavBar from '@/components/NavBar/NavBar'
import Hero from '@/components/Hero/Hero'
import FeaturesDisplay from '@/components/FeaturesDisplay/FeaturesDisplay'
import Footer from '@/components/Footer/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Bugtracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <div className="layout">
          <Hero />
          <FeaturesDisplay />
        </div>
        <Footer />
      </main>
    </>
  )
}
