import Head from 'next/head'
import Hero from '@/components/Hero/Hero'
import FeaturesDisplay from '@/components/FeaturesDisplay/FeaturesDisplay'
import Layout from '@/layouts/layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Bugtracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Hero />
          <FeaturesDisplay />
        </Layout>
      </main>
    </>
  )
}
