import Footer from '@/components/Footer/Footer'
import NavBar from '@/components/NavBar/NavBar'
import Head from 'next/head'
import { type ReactNode, type FC } from 'react'

interface props {
  title?: string
  children: ReactNode
}

const Layout: FC<props> = (props) => {
  return (
    <>
      <Head>
        <title>{props.title ? props.title : 'BugTracker'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, user-scalable=no, shrink-to-fit=no, viewport-fit=cover"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <NavBar />
        <div className="layout">{props.children}</div>
        <Footer />
      </main>
    </>
  )
}

export default Layout
