name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout server code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.5'
      - name: Test
        working-directory: ./server
        run: go test ./...

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./client
        run: npm install
      - name: Test
        working-directory: ./client
        run: npm test